use_frameworks!

platform :ios, '8.0'

target 'OnepiecedWorking_Example' do
  pod 'OnepiecedWorking', :path => '../'

  target 'OnepiecedWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
